# Generated by Django 5.2.10 on 2026-01-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_dept_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='image',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
