# Generated by Django 6.0.4 on 2026-04-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='test.png', null=True, upload_to='image'),
        ),
    ]
