# Generated by Django 6.0.4 on 2026-05-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
