# Generated by Django 6.0.4 on 2026-05-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_student_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
