# Generated by Django 5.2.8 on 2025-12-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_rollno_student_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='test.png', upload_to='image'),
        ),
    ]
